version: '3.8'
services:
  nginx:
    image: nginx:1.15
    ports:
      - "80:80"
    volumes:
      - ./laravel:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./laravel:/var/www/html

  composer:
    container_name: composer
    image: composer:latest
    volumes:
      - ./laravel:/app
    entrypoint: composer

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel_sample_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: laravel_sample_user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "53306:3306"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - docker_sample_mysql_data:/var/lib/mysql

  mail:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - mail_sample_dir:/tmp

volumes:
  docker_sample_mysql_data:
    driver: local
  mail_sample_dir:
    driver: local